-- Query 1
-- Show total sales for each product sold

SELECT PRODUCTID, SUM(FINALTOTAL) AS TOTAL_ORDER_AMOUNT
FROM ORDERDETAILS
GROUP BY PRODUCTID
ORDER BY  TOTAL_ORDER_AMOUNT DESC;



-- Query 2
-- Identify the top 3 products with the highest total sales

SELECT PRODUCTID, SUM(QUANTITY) AS TOTAL_QUANTITY
	, SUM(FINALTOTAL) AS 'TOTAL VOLUME'
FROM ORDERDETAILS
GROUP BY PRODUCTID
ORDER BY TOTAL_QUANTITY DESC
LIMIT 3;


-- Query 3
-- Identify customers with total orders over $1000

SELECT CUSTOMERID, SUM(TOTALPAID) AS TOTAL_ORDER_VALUE
FROM ORDERS
GROUP BY CUSTOMERID
HAVING TOTAL_ORDER_VALUE > 1000;


-- Query 4
-- Show each product's name with its total order amount

SELECT P.PRODUCTNAME, P.PRODUCTID,
	SUM(OD.FINALTOTAL) AS TOTAL_ORDER_AMOUNT
FROM ORDERDETAILS OD
INNER JOIN PRODUCTS P ON OD.PRODUCTID = P.PRODUCTID
GROUP BY OD.PRODUCTID, P.PRODUCTNAME;



-- Query 5
-- Find total quantity ordered for each product and identify products never ordered

SELECT P.PRODUCTID, 
	P.PRODUCTNAME, 
    COALESCE(SUM(QUANTITY), 0) AS TOTAL_QUANTITY_ORDERED
FROM PRODUCTS P 
LEFT JOIN ORDERDETAILS OD ON P.PRODUCTID = OD.PRODUCTID
GROUP BY P.PRODUCTID, P.PRODUCTNAME
ORDER BY TOTAL_QUANTITY_ORDERED DESC;




-- Query 6
-- custoemrs living in the same city

SELECT A.FIRSTNAME AS CUSTOMER1, 
		B.FIRSTNAME AS CUSTOMER2,
        A.CITY
FROM CUSTOMERS A
JOIN CUSTOMERS B
ON A.CUSTOMERID != B.CUSTOMERID AND A.CITY = B.CITY;














